"""
Django settings for TallerMecanico project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(u$$6imr2-zl&2!2fphx)&iclh#wrnp_0%-lr5dorhljod-5*7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Taller',
]

JAZZMIN_SETTINGS = {
    "site_title": "Taller Mecánico Admin",
    "site_header": "Panel de Administración",
    "site_brand": "Taller Mecánico",
    "site_logo": "img/carro.gif",  # Cambia por la ruta real de tu logo
    "welcome_sign": "Bienvenido al panel de administración del taller",
    "copyright": "© 2025 Taller Mecánico",
    
    # 🎨 Personalización de colores
    "primary_color": "#bd5d38",  # Marrón anaranjado
    "secondary_color": "#2C2F33",  # Gris oscuro para el fondo del menú
    "dark_mode_toggle": True,  # Habilita modo oscuro

    # 🎨 Configuración de la barra lateral (menú)
    "navigation_expanded": True,
    "show_ui_builder": False,
    "custom_css": "static/css/styles.css",  # Puedes agregar más estilos

    # 🎨 Iconos para los modelos en el panel
    "icons": {
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "app.Vehiculo": "fas fa-car",
        "app.Reparacion": "fas fa-tools",
        "app.Servicio": "fas fa-cogs",
    },
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TallerMecanico.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR /'Taller/Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TallerMecanico.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dbtaller',
        'USER': 'postgres',
        'PASSWORD': '#Hive2022',
        'HOST': 'localhost',  
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
import os
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'Taller/static'),  # Ruta de los archivos estáticos
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Carpeta donde se almacenarán los archivos estáticos

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
