# Generated by Django 5.1.5 on 2025-03-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
