# Generated by Django 5.1.5 on 2025-03-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taller', '0002_reparacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
